language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
  licenses:
    - 'android-sdk-preview-license.+'
    - 'android-sdk-license-.+'
script: ./gradlew clean check
