language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
  licenses:
    - 'android-sdk-preview-license.+'
    - 'android-sdk-license-.+'
script: ./gradlew clean check
